version: "2.3"

services:
  products_service:
    image: product_service
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - ".:/product_service"
    environment:
      APP_ENVIRONMENT: production
      HIGH_LIMIT: 5
      LOW_LIMIT: 20
      TIMEOUT: 120
      GATEWAY_ADDR: https://httpbin.org/post
      IP: 0.0.0.0
      PORT: 8080
      BASE_PATH: "/api/products"
      MongoDbURI: mongodb+srv://admin:admin@cluster0.cnciz.mongodb.net/products_service?retryWrites=true&w=majority
      MQ_PORT: 5672
      MQ_ADDRESS: rabbitmq
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    volumes:
      - /var/lib/rabbitmq
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  rabbitmq:
